version: '2.1'
services:
  scheduler1:
    build: ./
    container_name: scheduler1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/home/node
    ports:
      - "5000:5000"
      - "5858:5858"
    environment:
      NODE_ENV: dev
      PORT: 5000
  scheduler2:
    build: ./
    container_name: scheduler2
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/home/node
    ports:
      - "5001:5001"
      - "5859:5858"
    environment:
      NODE_ENV: dev
      PORT: 5001
  scheduler3:
    build: ./
    container_name: scheduler3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/home/node
    ports:
      - "5002:5002"
      - "5860:5858"
    environment:
      NODE_ENV: dev
      PORT: 5002
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scheduler_database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres:/scripts/postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
  etcd-1:
    container_name: etcd1
    image: quay.io/coreos/etcd:v3.4.15
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2500:2380"
      - "2379"
  etcd-2:
    container_name: etcd2
    image: quay.io/coreos/etcd:v3.4.15
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2501:2380"
      - "2379"
  etcd-3:
    container_name: etcd3
    image: quay.io/coreos/etcd:v3.4.15
    entrypoint: /usr/local/bin/etcd
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--initial-cluster-token=mys3cr3ttok3n'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
    ports:
      - "2502:2380"
      - "2379"
