version: '2.1'
services:
  scheduler:
    build: ./
    container_name: scheduler
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/home/node
    ports:
      - "5000:5000"
      - "5858:5858"
    environment:
      NODE_ENV: dev
      CLICKHOUSE_DATABASE: tracker_database
      CLICKHOUSE_EVENTS_TABLE: events
  postgres:
    image: postgres:12.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scheduler_database
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts/postgres:/scripts/postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
